---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: npm-install
  image: node:20-alpine
  commands: ["npm install"]

- name: test-node-20
  image: node:20-alpine
  commands: ["npm run test -s"]

- name: test-node-22
  image: node:22-alpine
  commands: ["npm run test -s"]

- name: release
  image: livingdocs/semantic-release:v2.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 3409014c20ee6a101095d731761b148b0121cc712bcf62241569cb32077b1b06

...
