---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: npm-install
  image: node:18-alpine
  commands: ["npm install"]

- name: test-node-16
  image: node:16-alpine
  commands: ["npm run test -s"]

- name: test-node-18
  image: node:18-alpine
  commands: ["npm run test -s"]

- name: release
  image: livingdocs/semantic-release:v2.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 2a80555ac4042eab01a04952af4eb216e88fcd5a818ffef5f26fadb733a436a9

...
